### ISSUE TITLE
RemoveItem fix

### ISSUE THREAD

**Issue by weewam** [jastrand/project-yohabit#4]
Alright! För removeItem är det lyckligtvis en enkel fix! Just nu är det två saker som går fel.

1. När du dispatchar `removeItem` i filen `HabitItem`, så är `itemIndex` inte definierat. Anledningen till detta är för att du inte skickat in den propen när du mapar över alla habits i `HabitSettings`. Enklaste lösningen är att faktiskt att strunta i `itemIndex` helt och hållet, i och med att habit redan är en del av din payload så räcker det. Så i `personalHabits` så ändrar du:
```
const { itemIndex } = action.payload -> const { habit } = action.payload
```

2. I find så jämför du Index med itemIndex, detta blir fel eftersom att Index i din loop är 0 indexerat, medan ditt itemIndex är 1 indexerat. Alltså hade du hamnat i en situation där fel habit tog bort ur listan. Det du istället ska jämföra är `item.id`
```
((item, index) => index !== itemIndex) -> ((item, index) => item.id !== habit.id)
```

**Comment by jastrand** [comment]
Done!
